epipeline {
    agent any
    stages {

        stage('Branch'){
            steps {
                echo "branch ${params.branchName.split('/').last()}"
            }
        }
        stage('checkout code') {
            steps {
                checkout scmGit(branches: [[name: "${params.branchName.split('/').last()}"]], extensions: [], userRemoteConfigs: [[url: 'https://github.com/error404100230/php-docker']])
          
            }
        }
        stage('build image') {
            steps {
                 withCredentials([string(credentialsId: 'DOCKER_REGISTRY_URL', variable: 'DOCKER_REGISTRY_URL')]) {
                      sh 'docker build -t ${DOCKER_REGISTRY_URL}/php:$BUILD_NUMBER .'
                 }
            }
        }
        stage('push image to hub') {
            steps {
              withCredentials([string(credentialsId: 'DOCKER_REGISTRY_URL', variable: 'DOCKER_REGISTRY_URL'), string(credentialsId: 'docker-hub-id', variable: 'hubpwd')]) {
                  
                  sh 'docker login -u ${DOCKER_REGISTRY_URL} -p ${hubpwd}'

                  sh 'docker push ${DOCKER_REGISTRY_URL}/php:$BUILD_NUMBER'

                  sh 'docker image rm ${DOCKER_REGISTRY_URL}/php:$BUILD_NUMBER';
              }
            }
        }

       stage('push telegram msg') {
            steps {
                script {
                   // sendTelegram("deployment done")

                    httpRequest (consoleLogResponseBody: true,
                        contentType: 'APPLICATION_JSON',
                        httpMode: 'POST',
                        url: "bot6476965277:AAGbiC51dS9RwGVo7y68OUJ3A1m5SbXVS4A/sendMessage?-4048256446&text='deployment success'",
                        validResponseCodes: '200')

                   // httpRequest httpMode: 'POST', ignoreSslErrors: true, responseHandle: 'NONE', url: 'https://api.telegram.org/bot6476965277:AAGbiC51dS9RwGVo7y68OUJ3A1m5SbXVS4A/sendMessage?chat_id=-4048256446&text="deployment success"', wrapAsMultipart: false
                }
            }
        }
        
    }
}

// def sendTelegram(message) {
//     def encodedMessage = URLEncoder.encode(message, "UTF-8")

//     withCredentials([string(credentialsId: 'telegramToken', variable: 'TOKEN'),
//     string(credentialsId: 'telegramChatId', variable: 'CHAT_ID')]) {

//         response = httpRequest (consoleLogResponseBody: true,
//                 contentType: 'APPLICATION_JSON',
//                 httpMode: 'GET',
//                 url: "https://api.telegram.org/bot$TOKEN/sendMessage?text=$encodedMessage&chat_id=$CHAT_ID&parse_mode=html&disable_web_page_preview=true",
//                 validResponseCodes: '200')
//         return response
//     }
// }

