pipeline {
    agent any
    stages {

        stage('Branch'){
            steps {
                echo "branch ${params.branchName}"
            }
        }
        stage('checkout code') {
            steps {
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/error404100230/php-docker']])
          
            }
        }
        stage('build image') {
            steps {
                      sh 'docker build -t vinsovann847/php:$BUILD_NUMBER .'
            }
        }
        stage('push image to hub') {
            steps {
              withCredentials([string(credentialsId: 'docker-hub-id', variable: 'hubpwd')]) {
                  sh 'docker login -u ${DOCKER_REGISTRY_URL} -p ${hubpwd}'
              }
              
              sh 'docker push ${DOCKER_REGISTRY_URL}/php:$BUILD_NUMBER'
            }
        }
    }
}
