epipeline {
    agent any
    stages {

        stage('Branch'){
            steps {
                echo "branch ${params.branchName.split('/').last()}"
            }
        }
        stage('checkout code') {
            steps {
                checkout scmGit(branches: [[name: "${params.branchName.split('/').last()}"]], extensions: [], userRemoteConfigs: [[url: 'https://github.com/error404100230/php-docker']])
          
            }
        }
        stage('build image') {
            steps {
                 withCredentials([string(credentialsId: 'DOCKER_REGISTRY_URL', variable: 'DOCKER_REGISTRY_URL')]) {
                      sh 'docker build -t ${DOCKER_REGISTRY_URL}/php:$BUILD_NUMBER .'
                 }
            }
        }
        stage('push image to hub') {
            steps {
              withCredentials([string(credentialsId: 'DOCKER_REGISTRY_URL', variable: 'DOCKER_REGISTRY_URL'), string(credentialsId: 'docker-hub-id', variable: 'hubpwd')]) {
                  
                  sh 'docker login -u ${DOCKER_REGISTRY_URL} -p ${hubpwd}'

                  sh 'docker push ${DOCKER_REGISTRY_URL}/php:$BUILD_NUMBER'

                  sh 'docker image rm ${DOCKER_REGISTRY_URL}/php:$BUILD_NUMBER';
              }
            }
        }

       stage('push telegram msg') {
            steps {
                script {
                 def jenkinsUrl = 'https://api.telegram.org/bot6476965277:AAGbiC51dS9RwGVo7y68OUJ3A1m5SbXVS4A/sendMessage?chat_id=-4048256446&text="done"' // Replace with your Jenkins URL
                

                    // Construct the cURL command
                    def curlCommand = "curl -X POST ${jenkinsUrl}"

                    // Execute the cURL command
                    sh curlCommand
                }
            }
        }
        
    }
}

